---
driver:
  name: vagrant
  vm_hostname: owncloud.local
  network:
  - ["forwarded_port", {guest:  80, host: 8080, auto_correct: true}]
  - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
  customize:
    memory: 512

provisioner:
  name: chef_solo
  require_chef_omnibus: true
  attributes:
    owncloud:
      server_aliases:
      - localhost
      config:
        trusted_domains:
        - localhost:8080
        - localhost:8443

platforms:
- name: centos-5.11
  run_list: recipe[selinux::disabled]
- name: centos-6.7
  run_list: recipe[selinux::disabled]
- name: centos-7.1
  run_list: recipe[selinux::disabled]
# No PHP 5.4 support:
# - name: debian-6.0.10
- name: debian-7.8
- name: debian-8.1
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: ubuntu-15.04

suites:
- name: mysql
  run_list: recipe[owncloud_test::mysql]
- name: postgresql
  run_list: recipe[owncloud_test::postgresql]
- name: sqlite
  excludes:
  # execute[run owncloud setup]: Writing to database failed
  - centos-5.11
  run_list: recipe[owncloud_test::sqlite]
- name: nginx
  run_list: recipe[owncloud_test::nginx]
