---
driver:
  name: vagrant
  vm_hostname: owncloud.local
  network:
  - ["forwarded_port", {guest:  80, host: 8080, auto_correct: true}]
  - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
  customize:
    memory: 512

provisioner:
  name: chef_solo
  require_chef_omnibus: true
  attributes:
    owncloud:
      server_aliases:
      - localhost
      config:
        trusted_domains:
        - localhost:8080
        - localhost:8443

platforms:
- name: centos-5.11
  run_list: recipe[selinux::disabled]
# (98)Address already in use: make_sock: could not bind to address 0.0.0.0:80
# https://github.com/svanzoest-cookbooks/apache2/issues/259
# - name: centos-6.7
#   run_list: recipe[selinux::disabled]
- name: centos-7.1
  run_list: recipe[selinux::disabled]
# No PHP 5.4 support:
# - name: debian-6.0.10
- name: debian-7.8
- name: debian-8.1
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: ubuntu-15.04

suites:
- name: mysql
  run_list: recipe[owncloud_test::mysql]
- name: postgresql
  run_list: recipe[owncloud_test::postgresql]
  excludes:
  - debian-7.8
  # Chef::Exceptions::Package: No candidate version available for postgresql-client-9.1
  - debian-8.1
  # https://github.com/hw-cookbooks/postgresql/issues/249
  - ubuntu-10.04
  - ubuntu-12.04
  - ubuntu-15.04
  # libpq.so: undefined reference to `SSL_[...]@OPENSSL_1.0.0'
  # https://github.com/hw-cookbooks/postgresql/issues/212
  - ubuntu-14.04
  # PostgreSQL >= 9 required
  - centos-5.11
- name: sqlite
  run_list: recipe[owncloud_test::sqlite]
  excludes:
  # execute[run owncloud setup]: Writing to database failed
  - centos-5.11
- name: nginx
  run_list: recipe[owncloud_test::nginx]
  excludes:
  # Error: Missing Dependency: php54w-cli >= 5.1.0-1 is needed by package
  # 1:php54w-pear-1.9.4-7.w5.noarch (installed)
  - centos-5.11
